name: sachiel_website
description: Sachiels AI Website

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ####### ####### #######
  blur: ^3.0.0
  ####### ####### #######

  ####### ####### #######
  cupertino_icons: ^1.0.2

  cloud_firestore: ^4.12.0
  ####### ####### #######

  ####### ####### #######
  firebase_core: ^2.2.0

  firebase_analytics: ^10.0.5
  firebase_crashlytics: ^3.0.5
  ####### ####### #######

  ####### ####### #######
  get: ^4.6.6
  ####### ####### #######

  ####### ####### #######
  share_plus: ^7.2.0

  shared_preferences: ^2.2.2
  ####### ####### #######


  ####### ####### #######
  url_launcher: ^6.1.5
  ####### ####### #######


  ####### ####### #######
  widget_mask: ^1.0.0+0
  ####### ####### #######



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/ai_status.png

    - assets/background.jpg

    - assets/candlestick_logo.png
    - assets/coming_soon.png
    - assets/cover.png

    - assets/download.png

    - assets/geeksempire_logo.png

    - assets/logo.png
    - assets/logo_icon.png

    - assets/menu.png

    - assets/newspaper.png

    - assets/privacy.png

    - assets/register_icon.png

    - assets/threads_icon.png
    - assets/tos.png
    - assets/twitter_icon.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.ttf
    - family: Handwriting
      fonts:
        - asset: fonts/waterfall.ttf
    - family: Electric
      fonts:
        - asset: fonts/electric.ttf